"""create nodes and edges tables

Revision ID: 4918b1cdc1e6
Revises:
Create Date: 2026-08-24 18:19:26.277633

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4918b1cdc1e6"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nodes",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_nodes_deleted_at"), "nodes", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_nodes_type"), "nodes", ["type"], unique=False)
    op.create_table(
        "edges",
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column(
            "attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["nodes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["nodes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_edges_deleted_at"), "edges", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_edges_source_id"), "edges", ["source_id"], unique=False)
    op.create_index(op.f("ix_edges_target_id"), "edges", ["target_id"], unique=False)
    op.create_index(op.f("ix_edges_type"), "edges", ["type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_edges_type"), table_name="edges")
    op.drop_index(op.f("ix_edges_target_id"), table_name="edges")
    op.drop_index(op.f("ix_edges_source_id"), table_name="edges")
    op.drop_index(op.f("ix_edges_deleted_at"), table_name="edges")
    op.drop_table("edges")
    op.drop_index(op.f("ix_nodes_type"), table_name="nodes")
    op.drop_index(op.f("ix_nodes_deleted_at"), table_name="nodes")
    op.drop_table("nodes")
    # ### end Alembic commands ###
