"""create_node_types_table

Revision ID: 7e6291f9785b
Revises: 4918b1cdc1e6
Create Date: 2026-08-30 15:51:15.804089

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7e6291f9785b"
down_revision: str | None = "4918b1cdc1e6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "node_types",
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "attributes_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_node_types_deleted_at"), "node_types", ["deleted_at"], unique=False
    )
    op.create_index(op.f("ix_node_types_slug"), "node_types", ["slug"], unique=True)
    op.execute("""
        INSERT INTO node_types (id, slug, label, created_at, updated_at)
        SELECT
            gen_random_uuid(),
            type           AS slug,
            initcap(type)  AS label,
            now(),
            now()
        FROM (SELECT DISTINCT type FROM nodes WHERE deleted_at IS NULL) t
        ON CONFLICT (slug) DO NOTHING
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_node_types_slug"), table_name="node_types")
    op.drop_index(op.f("ix_node_types_deleted_at"), table_name="node_types")
    op.drop_table("node_types")
    # ### end Alembic commands ###
