"""create_edge_types_table

Revision ID: a3f81c2d9e04
Revises: 7e6291f9785b
Create Date: 2026-08-31 10:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a3f81c2d9e04"
down_revision: str | None = "7e6291f9785b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "edge_types",
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("reverse_label", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("directional", sa.Boolean(), nullable=False, server_default="true"),
        sa.Column(
            "attributes_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_edge_types_deleted_at"), "edge_types", ["deleted_at"], unique=False
    )
    op.create_index(op.f("ix_edge_types_slug"), "edge_types", ["slug"], unique=True)
    op.execute("""
        INSERT INTO edge_types (id, slug, label, directional, created_at, updated_at)
        SELECT
            gen_random_uuid(),
            type           AS slug,
            initcap(type)  AS label,
            true,
            now(),
            now()
        FROM (SELECT DISTINCT type FROM edges WHERE deleted_at IS NULL) t
        ON CONFLICT (slug) DO NOTHING
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_edge_types_slug"), table_name="edge_types")
    op.drop_index(op.f("ix_edge_types_deleted_at"), table_name="edge_types")
    op.drop_table("edge_types")
    # ### end Alembic commands ###
