repos:
  - repo: local
    hooks:
      - id: prettier
        name: prettier format
        entry: uv run poe format-frontend
        language: system
        types_or:
          - javascript
          - ts
          - json
          - svelte
          - css
          - markdown
        pass_filenames: false

      - id: eslint
        name: eslint check
        entry: uv run poe lint-frontend
        language: system
        types_or:
          - javascript
          - ts
          - svelte
        pass_filenames: false
