worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include      /etc/nginx/mime.types;
    default_type application/octet-stream;

    client_max_body_size 10m;
    limit_req_zone $binary_remote_addr zone=api:10m rate=10r/s;

    sendfile      on;
    tcp_nopush    on;
    keepalive_timeout 65;
    server_tokens off;

    access_log /dev/stdout;
    error_log  /dev/stderr warn;

    include /etc/nginx/conf.d/*.conf;
}
