[project]
name = "menagerist-workspace"
version = "0.0.0"
description = "A lightweight, self-hostable and flexible platform for organising the things you care about."
requires-python = ">=3.14"

[tool.uv]
package = false

[tool.uv.workspace]
members = [
    "backend"
]

[dependency-groups]
dev = [
    "prek>=0.4.14",
    "poethepoet>=0.48.0"
]

[tool.poe]
verbosity = -1

[tool.poe.tasks._install-hooks]
cmd = "prek install -f"
help = "Install or update local git hooks"

[tool.poe.tasks.format-backend]
cmd = "ruff format ."
cwd = "backend"
help = "Format backend Python files with Ruff"

[tool.poe.tasks.lint-backend]
cmd = "ruff check ."
cwd = "backend"
help = "Lint backend Python files with Ruff"

[tool.poe.tasks.lint-backend-fix]
cmd = "ruff check . --fix"
cwd = "backend"
help = "Lint backend Python files with Ruff and apply safe fixes"

[tool.poe.tasks.typecheck-backend]
cmd = "mypy"
cwd = "backend"
help = "Type-check backend Python files with mypy"

[tool.poe.tasks.format]
sequence = ["format-backend"]
help = "Format all project code"

[tool.poe.tasks.lint]
sequence = ["lint-backend"]
help = "Lint all project code"

[tool.poe.tasks.typecheck]
sequence = ["typecheck-backend"]
help = "Type-check all project code"

[tool.poe.tasks._check-hooks]
shell = "prek run --all-files || prek run --all-files"
help = "Run all configured pre-commit checks against the full repository"

[tool.poe.tasks.check]
sequence = ["_check-hooks"]
help = "Run all configured checks against the full repository"

[tool.poe.tasks.init]
sequence = ["_install-hooks"]
help = "Initialize the local development environment"
