repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-ast
      - id: name-tests-test
        args:
          - --pytest-test-first

  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: uv run poe lint-backend-fix
        language: system
        types_or:
          - python
          - pyi
        pass_filenames: false

      - id: ruff-format
        name: ruff format
        entry: uv run poe format-backend
        language: system
        types_or:
          - python
          - pyi
        pass_filenames: false

      - id: mypy
        name: mypy
        entry: uv run poe typecheck-backend
        language: system
        pass_filenames: false

      - id: pytest
        name: pytest
        entry: uv run poe test-backend
        language: system
        pass_filenames: false
