[project]
name = "menagerist"
dynamic = ["version"]
description = "A lightweight, self-hostable and flexible platform for organising the things you care about."
requires-python = ">=3.14"
dependencies = []
license-files = [
    "../LICENSE"
]

[dependency-groups]
dev = [
    "mypy>=2.3.1",
    "ruff>=0.16.3",
]

[build-system]
requires = [
    "hatchling==1.29.0",
    "hatch-vcs==0.5.0",
    "calver-scm==1.4.1"
]

build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.targets.wheel]
packages = ["src/app"]

[tool.hatch.version.raw-options]
search_parent_directories = true
version_scheme = "calver-scm"
local_scheme = "no-local-version"

[tool.ruff]
fix = true
target-version = "py314"
line-length = 88

[tool.ruff.lint]
select = [
    "E",
    "W",
    "F",
    "I",
    "C90",
    "D",
    "UP",
    "B",
    "C4",
    "N",
    "SIM",
    "TC",
    "PT",
    "ANN",
    "TID",
    "RUF",
    "ISC",
]
ignore = [
    # Conflicts with Ruff formatter:
    # https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules
    "COM812",
    "COM819",
    "D206",
    "D300",
    "E111",
    "E114",
    "E117",
    "Q000",
    "Q001",
    "Q002",
    "Q003",
    "Q004",
    "W191",

    # Project-specific.
    "B008",
    "D100",
    "D104",
    "D107",
    "TC006",
]
fixable = ["ALL"]

[tool.ruff.lint.flake8-implicit-str-concat]
allow-multiline = false

[tool.ruff.lint.mccabe]
max-complexity = 8

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.isort]
known-first-party = ["app"]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]
combine-as-imports = true
split-on-trailing-comma = false

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"

[tool.mypy]
python_version = "3.14"
strict = true
files = ["src/app"]
mypy_path = "src"
explicit_package_bases = true
warn_unused_configs = true
show_error_codes = true
pretty = true
