/** A currency option: three-letter code, common name, and symbol when one exists. */
export type Currency = { code: string; name: string; symbol?: string };

// Active ISO 4217 currencies. Not every symbol-bearing currency lists one here - only where a
// single common symbol is unambiguous; everything else falls back to "{value} {code}" in the view.
export const CURRENCIES: Currency[] = [
	{ code: 'AED', name: 'UAE Dirham' },
	{ code: 'AFN', name: 'Afghan Afghani' },
	{ code: 'ALL', name: 'Albanian Lek' },
	{ code: 'AMD', name: 'Armenian Dram' },
	{ code: 'ANG', name: 'Netherlands Antillean Guilder' },
	{ code: 'AOA', name: 'Angolan Kwanza' },
	{ code: 'ARS', name: 'Argentine Peso', symbol: '$' },
	{ code: 'AUD', name: 'Australian Dollar', symbol: '$' },
	{ code: 'AWG', name: 'Aruban Florin' },
	{ code: 'AZN', name: 'Azerbaijani Manat' },
	{ code: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark' },
	{ code: 'BBD', name: 'Barbadian Dollar' },
	{ code: 'BDT', name: 'Bangladeshi Taka' },
	{ code: 'BGN', name: 'Bulgarian Lev' },
	{ code: 'BHD', name: 'Bahraini Dinar' },
	{ code: 'BIF', name: 'Burundian Franc' },
	{ code: 'BMD', name: 'Bermudan Dollar' },
	{ code: 'BND', name: 'Brunei Dollar' },
	{ code: 'BOB', name: 'Bolivian Boliviano' },
	{ code: 'BRL', name: 'Brazilian Real', symbol: 'R$' },
	{ code: 'BSD', name: 'Bahamian Dollar' },
	{ code: 'BTN', name: 'Bhutanese Ngultrum' },
	{ code: 'BWP', name: 'Botswanan Pula' },
	{ code: 'BYN', name: 'Belarusian Ruble' },
	{ code: 'BZD', name: 'Belize Dollar' },
	{ code: 'CAD', name: 'Canadian Dollar', symbol: '$' },
	{ code: 'CDF', name: 'Congolese Franc' },
	{ code: 'CHF', name: 'Swiss Franc' },
	{ code: 'CLP', name: 'Chilean Peso' },
	{ code: 'CNY', name: 'Chinese Yuan', symbol: '¥' },
	{ code: 'COP', name: 'Colombian Peso' },
	{ code: 'CRC', name: 'Costa Rican Colón' },
	{ code: 'CUP', name: 'Cuban Peso' },
	{ code: 'CVE', name: 'Cape Verdean Escudo' },
	{ code: 'CZK', name: 'Czech Koruna', symbol: 'Kč' },
	{ code: 'DJF', name: 'Djiboutian Franc' },
	{ code: 'DKK', name: 'Danish Krone' },
	{ code: 'DOP', name: 'Dominican Peso' },
	{ code: 'DZD', name: 'Algerian Dinar' },
	{ code: 'EGP', name: 'Egyptian Pound' },
	{ code: 'ERN', name: 'Eritrean Nakfa' },
	{ code: 'ETB', name: 'Ethiopian Birr' },
	{ code: 'EUR', name: 'Euro', symbol: '€' },
	{ code: 'FJD', name: 'Fijian Dollar' },
	{ code: 'FKP', name: 'Falkland Islands Pound' },
	{ code: 'GBP', name: 'British Pound', symbol: '£' },
	{ code: 'GEL', name: 'Georgian Lari' },
	{ code: 'GHS', name: 'Ghanaian Cedi' },
	{ code: 'GIP', name: 'Gibraltar Pound' },
	{ code: 'GMD', name: 'Gambian Dalasi' },
	{ code: 'GNF', name: 'Guinean Franc' },
	{ code: 'GTQ', name: 'Guatemalan Quetzal' },
	{ code: 'GYD', name: 'Guyanaese Dollar' },
	{ code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK$' },
	{ code: 'HNL', name: 'Honduran Lempira' },
	{ code: 'HTG', name: 'Haitian Gourde' },
	{ code: 'HUF', name: 'Hungarian Forint' },
	{ code: 'IDR', name: 'Indonesian Rupiah' },
	{ code: 'ILS', name: 'Israeli New Shekel', symbol: '₪' },
	{ code: 'INR', name: 'Indian Rupee', symbol: '₹' },
	{ code: 'IQD', name: 'Iraqi Dinar' },
	{ code: 'IRR', name: 'Iranian Rial' },
	{ code: 'ISK', name: 'Icelandic Króna' },
	{ code: 'JMD', name: 'Jamaican Dollar' },
	{ code: 'JOD', name: 'Jordanian Dinar' },
	{ code: 'JPY', name: 'Japanese Yen', symbol: '¥' },
	{ code: 'KES', name: 'Kenyan Shilling' },
	{ code: 'KGS', name: 'Kyrgystani Som' },
	{ code: 'KHR', name: 'Cambodian Riel' },
	{ code: 'KMF', name: 'Comorian Franc' },
	{ code: 'KPW', name: 'North Korean Won' },
	{ code: 'KRW', name: 'South Korean Won', symbol: '₩' },
	{ code: 'KWD', name: 'Kuwaiti Dinar' },
	{ code: 'KYD', name: 'Cayman Islands Dollar' },
	{ code: 'KZT', name: 'Kazakhstani Tenge' },
	{ code: 'LAK', name: 'Laotian Kip' },
	{ code: 'LBP', name: 'Lebanese Pound' },
	{ code: 'LKR', name: 'Sri Lankan Rupee' },
	{ code: 'LRD', name: 'Liberian Dollar' },
	{ code: 'LSL', name: 'Lesotho Loti' },
	{ code: 'LYD', name: 'Libyan Dinar' },
	{ code: 'MAD', name: 'Moroccan Dirham' },
	{ code: 'MDL', name: 'Moldovan Leu' },
	{ code: 'MGA', name: 'Malagasy Ariary' },
	{ code: 'MKD', name: 'Macedonian Denar' },
	{ code: 'MMK', name: 'Myanmar Kyat' },
	{ code: 'MNT', name: 'Mongolian Tugrik' },
	{ code: 'MOP', name: 'Macanese Pataca' },
	{ code: 'MRU', name: 'Mauritanian Ouguiya' },
	{ code: 'MUR', name: 'Mauritian Rupee' },
	{ code: 'MVR', name: 'Maldivian Rufiyaa' },
	{ code: 'MWK', name: 'Malawian Kwacha' },
	{ code: 'MXN', name: 'Mexican Peso', symbol: '$' },
	{ code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM' },
	{ code: 'MZN', name: 'Mozambican Metical' },
	{ code: 'NAD', name: 'Namibian Dollar' },
	{ code: 'NGN', name: 'Nigerian Naira', symbol: '₦' },
	{ code: 'NIO', name: 'Nicaraguan Córdoba' },
	{ code: 'NOK', name: 'Norwegian Krone' },
	{ code: 'NPR', name: 'Nepalese Rupee' },
	{ code: 'NZD', name: 'New Zealand Dollar', symbol: '$' },
	{ code: 'OMR', name: 'Omani Rial' },
	{ code: 'PAB', name: 'Panamanian Balboa' },
	{ code: 'PEN', name: 'Peruvian Sol' },
	{ code: 'PGK', name: 'Papua New Guinean Kina' },
	{ code: 'PHP', name: 'Philippine Peso', symbol: '₱' },
	{ code: 'PKR', name: 'Pakistani Rupee' },
	{ code: 'PLN', name: 'Polish Zloty', symbol: 'zł' },
	{ code: 'PYG', name: 'Paraguayan Guarani' },
	{ code: 'QAR', name: 'Qatari Rial' },
	{ code: 'RON', name: 'Romanian Leu' },
	{ code: 'RSD', name: 'Serbian Dinar' },
	{ code: 'RUB', name: 'Russian Ruble', symbol: '₽' },
	{ code: 'RWF', name: 'Rwandan Franc' },
	{ code: 'SAR', name: 'Saudi Riyal' },
	{ code: 'SBD', name: 'Solomon Islands Dollar' },
	{ code: 'SCR', name: 'Seychellois Rupee' },
	{ code: 'SDG', name: 'Sudanese Pound' },
	{ code: 'SEK', name: 'Swedish Krona' },
	{ code: 'SGD', name: 'Singapore Dollar', symbol: 'S$' },
	{ code: 'SHP', name: 'Saint Helena Pound' },
	{ code: 'SLE', name: 'Sierra Leonean Leone' },
	{ code: 'SOS', name: 'Somali Shilling' },
	{ code: 'SRD', name: 'Surinamese Dollar' },
	{ code: 'SSP', name: 'South Sudanese Pound' },
	{ code: 'STN', name: 'São Tomé and Príncipe Dobra' },
	{ code: 'SYP', name: 'Syrian Pound' },
	{ code: 'SZL', name: 'Swazi Lilangeni' },
	{ code: 'THB', name: 'Thai Baht', symbol: '฿' },
	{ code: 'TJS', name: 'Tajikistani Somoni' },
	{ code: 'TMT', name: 'Turkmenistani Manat' },
	{ code: 'TND', name: 'Tunisian Dinar' },
	{ code: 'TOP', name: "Tongan Pa'anga" },
	{ code: 'TRY', name: 'Turkish Lira', symbol: '₺' },
	{ code: 'TTD', name: 'Trinidad and Tobago Dollar' },
	{ code: 'TWD', name: 'New Taiwan Dollar', symbol: 'NT$' },
	{ code: 'TZS', name: 'Tanzanian Shilling' },
	{ code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴' },
	{ code: 'UGX', name: 'Ugandan Shilling' },
	{ code: 'USD', name: 'US Dollar', symbol: '$' },
	{ code: 'UYU', name: 'Uruguayan Peso' },
	{ code: 'UZS', name: 'Uzbekistan Som' },
	{ code: 'VES', name: 'Venezuelan Bolívar Soberano' },
	{ code: 'VND', name: 'Vietnamese Dong', symbol: '₫' },
	{ code: 'VUV', name: 'Vanuatu Vatu' },
	{ code: 'WST', name: 'Samoan Tala' },
	{ code: 'XAF', name: 'Central African CFA Franc' },
	{ code: 'XCD', name: 'East Caribbean Dollar' },
	{ code: 'XOF', name: 'West African CFA Franc' },
	{ code: 'XPF', name: 'CFP Franc' },
	{ code: 'YER', name: 'Yemeni Rial' },
	{ code: 'ZAR', name: 'South African Rand', symbol: 'R' },
	{ code: 'ZMW', name: 'Zambian Kwacha' },
	{ code: 'ZWL', name: 'Zimbabwean Dollar' },
	// Fictional currencies use app-local codes and are not ISO 4217 currencies.
	{ code: 'GPL', name: 'Gold-Pressed Latinum' },
	{ code: 'ZRU', name: 'Hyrule Rupee' }
];

const byCode = new Map(CURRENCIES.map((c) => [c.code, c]));

export function currencyByCode(code: string): Currency | undefined {
	return byCode.get(code);
}
